### ISSUE TITLE
[feat] - Eureka, DiscoveryService Github Actions CI & CD 구축

### ISSUE THREAD

**Issue by sasca37** [freediving-community/api-server#30]
# Discovery, Gateway Service CI & CD 적용하기 

## Eureka 서버 

http://ec2-13-125-189-243.ap-northeast-2.compute.amazonaws.com:8761/

![Image](https://github.com/freediving-community/api-server/assets/81945553/7bd2f5fc-6cd9-4f20-b6ba-2605b52780d1)

## Github Actions 설정 
```
name: CI & CD for discovery-service
```

- WorkFlow에서 조회할 서비스명 지정 

```
on:
  push:
    paths:
      - 'discovery-service/**'
    branches: [ "main" ]
```

- push 트리거를 지정할 서비스경로 지정 

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Create application-dev.yml
        run: |
          touch ./discovery-service/src/main/resources/application-dev.yml
          echo "${{ secrets.DISCOVERY_APPLICATION_DEV_YML }}" > ./discovery-service/src/main/resources/application-dev.yml
```

- Github Secrets에서 관리하는 변수에 application-dev.yml을 생성 후 생성하도록 지정

```
  - name: Build with Gradle
    run: |
      ./gradlew discovery-service:build
```

- 사용할 서비스 gradle build 작업

```
      - name: Docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/discovery-service ./discovery-service
          docker push ${{ secrets.DOCKER_REPO }}/discovery-service
```

- docker hub에 push 과정 (secrets 에 등록한 계정을 공용계정으로 사용하면 될듯 합니다.)

```
      - name: AWS EC2 remote ssh and command by appleboy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DISCOVERY_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.DISCOVERY_EC2_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_REPO }}/discovery-service
            sudo docker stop $(sudo docker ps -a | grep discovery-service | awk '{print $1}')
            sudo docker rm $(sudo docker ps -a | grep discovery-service | awk '{print $1}')
            sudo docker image prune -a -f
            sudo docker-compose -p discovery -f /docker/docker-compose-discovery-${{ secrets.SERVER_PROFILE }}.yml down --rmi all
            sudo docker-compose -p discovery -f /docker/docker-compose-discovery-${{ secrets.SERVER_PROFILE }}.yml up -d
```

- hosts : EC2 EIP 입력 
- key : pem 키 정보 입력 (---- BEGIN ~ END ---- 까지)
- EC2 SSH 접속 후 이미지 실행
   - Eureka, Discovery의 경우 동일 서버를 사용하고 있어, 지정한 서비스명만 볼륨/이미지 제거 후 실행되도록 설정하였습니다.

## Dockerfile 설정 
```
FROM openjdk:21
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} ./discovery-service.jar
ENV TZ=Asia/Seoul
# DEV ENTRYPOINT
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=dev", "./discovery-service.jar"]
```
- 자바 21 / dev profile로 이미지 빌드되도록 지정 

```
jar {
    enabled = false
}
```
- build 시 plain.jar 생성 제외를 서비스 build.gradle에 제외 설정 추가하였습니다.

## EC2 docker compose 설정 
```
# https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.8"
services:
  web:
    container_name: discovery-service
    image: buddyme/discovery-service
    ports:
      - '8761:8761'
```
- EC2 내 이미지 pull 받은 후 docker-compose 실행을 위한 코드 작성
