### ISSUE TITLE
[feat] - Swagger 통합

### ISSUE THREAD

**Issue by RedJunHee** [freediving-community/api-server#51]
Spring Cloud Gateway서비스에 WebFlux Swagger UI 적용하여 각 서비스 Swagger UI 통합.

### 의존성 주입
스프링 클라우드 게이트웨이는 WebFlux 프레임워크 기반으로 작동되므로 WebFlux UI 추가.
```gradle
implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.0.2'
```

### 게이트웨이 Swagger UI 활성화 및 서비스 Swagger UI Docs 추가
```yml 
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: API Gateway Service
        url: /v3/api-docs
      - name: member-service
        url: http://localhost:${server.port}/v3/api-docs/member-service
      - name: buddy-service
        url: http://localhost:${server.port}/v3/api-docs/buddy-service
      - name: community-service
        url: http://localhost:${server.port}/v3/api-docs/community-service
```

### Routing 설정
각 서비스의 /v3/api-docs서비스에 대해서 AuthorizationFilter 필터 없는 라우팅을 설정.
이 설정은 AuthorizationFilter를 사용하는 Service/** 라우팅보다 우선순위를 가져야함
**우선순위는 yml에 상단에 위치하면 우선순위**
```yml
  # Buddy Service Route Set
  - id: buddy-service-swagger-ui # Swagger UI 라우팅 우선순위로 설정되어야 하므로 buddy-service-with-auth 보다 위에 위치함.
    uri: lb://BUDDY-SERVICE
    predicates:
      - Path=/buddy-service/v3/api-docs
    filters:
      - RewritePath=/buddy-service/(?<segment>.*), /$\{segment}
  - id: buddy-service-with-auth  # API 설정
    predicates:
      - Path=/buddy-service/**
    uri: lb://BUDDY-SERVICE
    filters:
      - AuthorizationFilter
      - RewritePath=/buddy-service/api/(?<segment>.*), /api/$\{segment}
```

각 서비스의 v3/api-docs를 호출하기 위한 라우팅 설정.   
API Gateway Swaager UI docs 목록을 클릭하면 아래의 openapi 라우팅을 통해 buddy-service-swagger-ui  라우팅으로 전달됩니다.
```yml
  - id: openapi
    uri: http://localhost:${server.port}
    predicates:
      - Path=/v3/api-docs/**
    filters:
      - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
```

### 각 서비스 Swagger UI 의존성 주입
스프링 3.xx 부터는 Swager 2버전을 사용해함.
```gradle
   implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.2'
```

통합된 Swagger UI 주소
http://ApiGateway:port/swagger-ui.html

![Image](https://github.com/freediving-community/api-server/assets/46863381/afa06697-1efc-40e9-9cd9-d8e129bab072)
